name: RabbitMQ Components Nuget

on:
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Build and pack RabbitMQ.Components
      run: sudo /home/runner/.dotnet/dotnet build ./Messaging/RoyalCode.RabbitMQ.Components/RoyalCode.RabbitMQ.Components.csproj -c Release
      
    - name: publish nuget package
      run: sudo /home/runner/.dotnet/dotnet nuget push ./**/RoyalCode.RabbitMQ.Components.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
